package Implementation;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author ahmed
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

public class BookingController {
    private Booking booking;
    private JTextField passengerNameF;
    private JTextField passengerNoF;
    private JTextField passengerEmailF;
    private JTextField flightNoF;
    private JTextField seatClassF;
    private JTextField bagsNoF;
    private JTextField bagsWF;
    private JTextField mealPreF;
    private JTextField paymentMethodF;
    
    public BookingController(){
        booking = new Booking();
        createGUI();
    }
    private void createGUI(){
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PassengerNameLABEL = new javax.swing.JLabel();
        PassengerNameFIELD = new javax.swing.JTextField();
        PassengerEmailLABEL = new javax.swing.JLabel();
        PassengerEmailFIELD = new javax.swing.JTextField();
        FlightNoLABEL = new javax.swing.JLabel();
        PhoneNoLABEL = new javax.swing.JLabel();
        PhoneNoFIELD = new javax.swing.JTextField();
        SeatClassLABEL = new javax.swing.JLabel();
        bagsNoLABEL = new javax.swing.JLabel();
        MealPreLABEL = new javax.swing.JLabel();
        baggageWeightLABEL = new javax.swing.JLabel();
        bagsNoFIELD = new javax.swing.JTextField();
        SeatClassFIELD = new javax.swing.JTextField();
        baggageWeightFIELD = new javax.swing.JTextField();
        MealPreFIELD = new javax.swing.JTextField();
        PaymentMethodLABEL = new javax.swing.JLabel();
        paymentMethodFIELD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FlightNoFIELD = new javax.swing.JTextField();
        BOOKbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PassengerNameLABEL.setForeground(new java.awt.Color(204, 0, 51));
        PassengerNameLABEL.setText("PassName");

        PassengerNameFIELD.setForeground(new java.awt.Color(255, 0, 51));

        PassengerEmailLABEL.setText("passEmail");

        PassengerEmailFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassengerEmailFIELDActionPerformed(evt);
            }
        });

        FlightNoLABEL.setForeground(new java.awt.Color(255, 0, 0));
        FlightNoLABEL.setText("FlightNo.");

        PhoneNoLABEL.setText("PhoneNo.");

        SeatClassLABEL.setText("SeatClass");

        bagsNoLABEL.setText("BagsNo.");

        MealPreLABEL.setText("MealPre");

        baggageWeightLABEL.setText("BagW");

        PaymentMethodLABEL.setText("PaymentMethod");

        paymentMethodFIELD.setText("Credit/paypal");

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel9.setText("FLight Booking");

        FlightNoFIELD.setForeground(new java.awt.Color(204, 0, 51));

        BOOKbutton.setForeground(new java.awt.Color(0, 102, 204));
        BOOKbutton.setText("BOOK");
        BOOKbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PassengerNameLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PassengerEmailLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SeatClassLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(PassengerNameFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(PhoneNoLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(SeatClassFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(PaymentMethodLABEL)
                                            .addGap(18, 18, 18)
                                            .addComponent(paymentMethodFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(PassengerEmailFIELD)
                                            .addComponent(MealPreFIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(baggageWeightLABEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bagsNoLABEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(FlightNoLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(MealPreLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BOOKbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bagsNoFIELD, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PhoneNoFIELD, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FlightNoFIELD, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(baggageWeightFIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassengerNameLABEL)
                    .addComponent(PassengerNameFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNoLABEL)
                    .addComponent(PhoneNoFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassengerEmailLABEL)
                    .addComponent(PassengerEmailFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightNoLABEL)
                    .addComponent(FlightNoFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SeatClassLABEL)
                        .addComponent(SeatClassFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bagsNoLABEL)
                        .addComponent(bagsNoFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(baggageWeightLABEL)
                        .addComponent(baggageWeightFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MealPreLABEL)
                        .addComponent(MealPreFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentMethodLABEL)
                    .addComponent(paymentMethodFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(BOOKbutton)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>                                   

    private void BOOKbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                           
if(PassengerNameFIELD.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Please fill out PassengerName");
    }                                          
else if(PassengerEmailFIELD.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Please fill out PassengerEmail");
}
else if(PhoneNoFIELD.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Please fill out PhoneNo.");
}
else if (FlightNoFIELD.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Please fill out FlightNo.");
}
else if(SeatClassFIELD.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Please fill out SeatClass");
}
else if(MealPreFIELD.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Please fill out MealPre");
}
else if(bagsNoFIELD.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Please fill out bagsNo.");
}
else if(baggageWeightFIELD.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Please fill out baggageWeight");
}
else if(paymentMethodFIELD.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Please fill out PaymentMethod");
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BOOKbutton;
    private javax.swing.JTextField FlightNoFIELD;
    private javax.swing.JLabel FlightNoLABEL;
    private javax.swing.JTextField MealPreFIELD;
    private javax.swing.JLabel MealPreLABEL;
    private javax.swing.JTextField PassengerEmailFIELD;
    private javax.swing.JLabel PassengerEmailLABEL;
    private javax.swing.JTextField PassengerNameFIELD;
    private javax.swing.JLabel PassengerNameLABEL;
    private javax.swing.JLabel PaymentMethodLABEL;
    private javax.swing.JTextField PhoneNoFIELD;
    private javax.swing.JLabel PhoneNoLABEL;
    private javax.swing.JTextField SeatClassFIELD;
    private javax.swing.JLabel SeatClassLABEL;
    private javax.swing.JTextField baggageWeightFIELD;
    private javax.swing.JLabel baggageWeightLABEL;
    private javax.swing.JTextField bagsNoFIELD;
    private javax.swing.JLabel bagsNoLABEL;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField paymentMethodFIELD;
    // End of variables declaration                   
}
    
        


    private class BOOKINGbuttonListener implements ActionListener {
        public void actionPerformed(ActionEvent e){
            String name =passengerNameFIELD.getText();
            String mail=PassengerEmailFIELD.getText();
            String phone=PassengerNoFIELD.getText();
            String flight = flightNoFIELD.getText();
            String SeatClass = SeatClassFIELD.getText();
            String meal = MealPreFIELD.getText();
            String bags=bagsNoFIELD.getText();
            String weight=baggageWeightFIELD.getText();
            String payment=PaymentMethodFIELD.getText();
            booking.setName(name);
           booking.setmail(mail);
           booking.setphone(phone);
           booking.setflight(flight);
           booking.setSeatClass(SeatClass);
           booking.setmeal(meal);
           booking.setbagsNo(bags);
           booking.setbaggageWeight(weight);
           booking.setpayment(payment);
           JOptionPane.showMessageDialog(null, "BOOKING COMPLETE!");
        }
        public static void main(String[]args){
BookingController controller = new BookingController();
}
        }